source "https://rubygems.org"

gem 'danger'
gem 'slather'
gem 'danger-swiftlint'
gem 'danger-xcode_summary'
gem 'danger-slather'
gem 'xcpretty-json-formatter'
gem 'rest-client'
gem 'cocoapods', '1.6.1'
gem 'xcode-install'
