# Import the Dangerfile of the SMF-iOS-Fastlane commons repo
fastlane_commmons_folder = ENV['FASTLANE_COMMONS_FOLDER']

puts fastlane_commons_folder

danger.import_dangerfile(path: "#{fastlane_commmons_folder}/danger")

# Add custom logic here
